/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=dev/coding-finale/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=FinaleEnv dev/coding-finale/env.d.ts` (hash: 5c67425bad8cb107f6fd761bdd92a91b)
interface __BaseEnv_FinaleEnv {
	LAB_TOKEN: string;
	FINALES: DurableObjectNamespace<import("./worker").FinaleObject>;
	SANDBOXES: DurableObjectNamespace<import("./worker").FinaleSandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "FinaleObject" | "FinaleSandbox";
	}
	interface Env extends __BaseEnv_FinaleEnv {}
}
interface FinaleEnv extends __BaseEnv_FinaleEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LAB_TOKEN">> {}
}
